name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
         with:
          ref: ${{ github.event.pull_request.head.sha }}
       - name: Simple JS action
         id: greet
         uses: actions/hello-world-javascript-action@main
         with:
           who-to-greet: 'Mona the Octocat'
       - name: Log Greeting time
         run: echo "${{ steps.greet.outputs.time }}"
       - name: Hello world action step
         id: hello
         uses: ./.github/actions/validate
         with:
           who-to-greet: 'Vivek the Octocat'
       - run: echo ${{ steps.hello.outputs.time }}
       - run: echo ${{ steps }}
       - run: echo ${{ jobs }}

