name: Shell Commands

on: [push]
env:
   envNameRoot: stage
jobs:
  run-shell-command:
     runs-on: ubuntu-latest
     env:
       envName: stage
     steps:
       - name: echo a string
         run: echo "Env name= ${envName}"
       - name: multi line 
         run: | 
           hostname
           env|sort
